[project]
name = "meshcli"
version = "0.1.0"
description = "Meshtastic CLI tool."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "textual>=3.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
