from _typeshed import Incomplete
from meshtastic.protobuf import portnums_pb2 as portnums_pb2, remote_hardware_pb2 as remote_hardware_pb2
from meshtastic.util import our_exit as our_exit

def onGPIOreceive(packet, interface) -> None: ...

class RemoteHardwareClient:
    iface: Incomplete
    channelIndex: Incomplete
    def __init__(self, iface) -> None: ...
    def writeGPIOs(self, nodeid, mask, vals): ...
    def readGPIOs(self, nodeid, mask, onResponse=None): ...
    def watchGPIOs(self, nodeid, mask): ...
