from .topicobj import Topic as Topic
from enum import IntEnum

class ITopicTreeVisitor: ...

class TreeTraversal(IntEnum):
    DEPTH = ...
    BREADTH = ...
    MAP = ...

class TopicTreeTraverser:
    def __init__(self, visitor: ITopicTreeVisitor = None) -> None: ...
    def setVisitor(self, visitor: ITopicTreeVisitor): ...
    def traverse(self, topicObj: Topic, how: TreeTraversal = ..., onlyFiltered: bool = True): ...
