name: validate-code-style

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"

      - name: Run linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"
